
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        rbRed = new javax.swing.JRadioButton();
        rbBlue = new javax.swing.JRadioButton();
        rbGreen = new javax.swing.JRadioButton();
        rbBlack = new javax.swing.JRadioButton();
        panel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup.add(rbRed);
        rbRed.setText("Red");
        rbRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRedMouseClicked(evt);
            }
        });

        buttonGroup.add(rbBlue);
        rbBlue.setText("Blue");
        rbBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbBlueMouseClicked(evt);
            }
        });

        buttonGroup.add(rbGreen);
        rbGreen.setText("Green");
        rbGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbGreenMouseClicked(evt);
            }
        });

        buttonGroup.add(rbBlack);
        rbBlack.setText("Black");
        rbBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbBlackMouseClicked(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Choose a color");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbBlack)
                    .addComponent(rbGreen)
                    .addComponent(rbBlue)
                    .addComponent(rbRed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rbRed)
                .addGap(18, 18, 18)
                .addComponent(rbBlue)
                .addGap(18, 18, 18)
                .addComponent(rbGreen)
                .addGap(18, 18, 18)
                .addComponent(rbBlack)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRedMouseClicked
        // TODO add your handling code here:
        label.setText("Red is selected");
        label.setForeground(Color.white);
        panel.setBackground(Color.red);
    }//GEN-LAST:event_rbRedMouseClicked

    private void rbBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbBlueMouseClicked
        // TODO add your handling code here:
        label.setText("Blue is selected");
        label.setForeground(Color.white);
        panel.setBackground(Color.blue);
    }//GEN-LAST:event_rbBlueMouseClicked

    private void rbGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbGreenMouseClicked
        // TODO add your handling code here:
        label.setText("Green is selected");
        label.setForeground(Color.white);
        panel.setBackground(Color.green);
    }//GEN-LAST:event_rbGreenMouseClicked

    private void rbBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbBlackMouseClicked
        // TODO add your handling code here:
        label.setText("Black is selected");
        label.setForeground(Color.white);
        panel.setBackground(Color.black);
    }//GEN-LAST:event_rbBlackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rbBlack;
    private javax.swing.JRadioButton rbBlue;
    private javax.swing.JRadioButton rbGreen;
    private javax.swing.JRadioButton rbRed;
    // End of variables declaration//GEN-END:variables
}
